logger: convert js to ts
The error that is mentioned below can be fixed by enabling
esModuleInterop:

```
logger.ts:1:8 - error TS1259: Module '"/bot/node_modules/winston/index"' can only be default-imported using the 'esModuleInterop' flag

1 import winston from 'winston';
         ~~~~~~~

  node_modules/winston/index.d.ts:213:1
    213 export = winston;
        ~~~~~~~~~~~~~~~~~
    This module is declared with 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
```