fix(validations): fix named export
As community may sometimes be null, I edited the
isDisputeSolver function to accept null, so we don't have to
do a null check over it.

```
bot/validations.ts:97:38 - error TS2345: Argument of type '(ICommunity & { _id: ObjectId; }) | null' is not assignable to parameter of type 'ICommunity'.
  Type 'null' is not assignable to type 'ICommunity'.

97     const isSolver = isDisputeSolver(community, user);
                                        ~~~~~~~~~

Found 1 error in bot/validations.ts:97
```